package com.example.brady.myapplication;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.hardware.Camera;
import android.os.AsyncTask;
import android.os.Bundle;
import android.provider.Settings;
import android.speech.tts.TextToSpeech;
import android.util.Log;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;

import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import org.json.JSONObject;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Locale;

import cat.lafosca.facecropper.FaceCropper;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener,Camera.ShutterCallback,Camera.PictureCallback,SurfaceHolder.Callback{
    /** {@link CardScrollView} to use as the main content view. */
    private CardScrollView mCardScroller;
    private SurfaceView mSurfaceView;
    private Camera cam;

    /**
     * {@link View} generated by {@link #buildView()}.
     */
    private View mView;

    private TextToSpeech mTts;
    private int  MY_DATA_CHECK_CODE =123;

    @Override
    protected void onActivityResult(
            int requestCode, int resultCode, Intent data) {
        if (requestCode == MY_DATA_CHECK_CODE) {
            if (resultCode == TextToSpeech.Engine.CHECK_VOICE_DATA_PASS) {
                // success, create the TTS instance
                mTts = new TextToSpeech(this, this);
            } else {
                // missing data, install it
                Intent installIntent = new Intent();
                installIntent.setAction(
                        TextToSpeech.Engine.ACTION_INSTALL_TTS_DATA);
                startActivity(installIntent);
            }
        }
    }

    private static final String TAG = "MyActivity";


    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        //mView = buildView();

        /* All the camera interaction is here */
        Settings.System.putInt(getContentResolver(), Settings.System.SCREEN_OFF_TIMEOUT, 600000);
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);//int flag, int mask
        this.requestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.surface);
        mSurfaceView = (SurfaceView) findViewById(R.id.surf);

        cam = Camera.open();
        snapPicture();

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });

        Intent checkIntent = new Intent();
        checkIntent.setAction(TextToSpeech.Engine.ACTION_CHECK_TTS_DATA);
        startActivityForResult(checkIntent, MY_DATA_CHECK_CODE);

    }

    @Override
    public void onShutter() {
        /* This is where we put shutter sound */
        return;
    }

    /**
     *  Callback interface used to supply image data from a photo capture.
     */
    @Override
    public void onPictureTaken(byte[] bytes, Camera camera) {
        FileOutputStream fos= null;

        /* Write byte array to jpeg file */
        try {
            File photo=new File(this.getCacheDir(), "3eyeout.jpg");
            if (photo.exists()) {
                photo.delete();
            }
            fos = new FileOutputStream(photo.getPath());
            fos.write(bytes);
            fos.close();
            startRecognition(photo.getPath());

//            PhotoAsyncTask task = new PhotoAsyncTask();
//            task.execute(photo.getPath());
        }
        catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        catch (IOException e){
            e.printStackTrace();
        }
        return;
    }

    public void startRecognition(String photoPath) {
        // crops image to face and scales it to 800 x 800
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inPreferredConfig = Bitmap.Config.ARGB_8888;
        Bitmap bitmap = BitmapFactory.decodeFile(photoPath, options);
        FaceCropper mFaceCropper = new FaceCropper();
        mFaceCropper.setMaxFaces(1);
        Bitmap cropped = mFaceCropper.getCroppedImage(bitmap);
        Bitmap scaled = Bitmap.createScaledBitmap(cropped, 800, 800, false);

        ImageView iv = new ImageView(this);
        iv.setImageBitmap(scaled);
        ((FrameLayout)findViewById(R.id.layout)).addView(iv);
    }

    @Override
    public void surfaceCreated(SurfaceHolder surfaceHolder) {
    }

    /**
     * Starts preview and takes picture.
     */
    @Override
    public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i2, int i3) {
        if(surfaceHolder.getSurface() == null || cam == null) {
            return;
        }

        //stop preview before make changes
        cam.stopPreview();

        //start preview with new setting
        try {
            cam.setPreviewDisplay(surfaceHolder);
            cam.startPreview();
            cam.takePicture(this,null,null,this);
        } catch (IOException e) {
            Log.e("MainActivity","problem setting up camera",e);
        }
    }

    /**
     * Stops preview and releases camera
     */
    @Override
    public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
        surfaceHolder.removeCallback(this);
        cam.lock();
        cam.stopPreview();
        cam.release();
        surfaceHolder = null;
    }

    private class PhotoAsyncTask extends AsyncTask<String, Void, JSONObject>{

        /* Makes Post request */
        @Override
        protected JSONObject doInBackground(String... strings) {
            return null;
        }

//        /* Parses JSON, reads result to user */
        @Override
        protected void onPostExecute(final JSONObject jsonObject) {
            super.onPostExecute(jsonObject);
        }
    }

    /* Camera stuff */
    protected void snapPicture() {
        SurfaceHolder holder = mSurfaceView.getHolder();
        holder.addCallback(this);
    }

    /**
     *  Runs after taking picture. Sets loading bar and reads "loading" out loud.
     */
    @Override
    protected void onResume() {
        super.onResume();
        findViewById(R.id.progressContainer).setVisibility(View.GONE);
        ((TextView) findViewById(R.id.textview)).setText(getString(R.string.loading));

    }

    @Override
    protected void onPause() {
        super.onPause();
    }

    /**
     * Builds a view using the {@link CardBuilder} class.
     */
    private View buildView() {
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

        card.setText(R.string.hello_world);
        return card.getView();
    }

    @Override
    public void onInit(int i) {
        Log.i("MainActivity", "Works: " + i);
        mTts.setLanguage(Locale.US);
    }

    @Override
    protected void onDestroy()
    {
        super.onDestroy();
        if ( mTts != null)
        {
            mTts.stop();
            mTts.shutdown();
        }
    }
}